### PR TITLE
Update landing page

### LINKED ISSUE #2931: Landing page module summaries
@dimasciput please add Anura.
Also please change the breakdown category for Fish and Anura to Conservation Status.
Thanks
Screen Shot 2022-02-01 at 8 58 50 AM
imas

### PR DESCRIPTION
**Pull request by Fanevanjanahary**
fixes #2931

image

### CODE REVIEW

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton what do you think about the colors?

**Comment by helendallas** [comment]
@jeremyshelton PLease cna you review these please

**Comment by jeremyshelton** [comment]
@Fanevanjanahary These categories look good 👍
Thank you. Now its just the color palette that needs adjustment.
FBIS color palette: 
FBIS_Colours

@helendallas @dimasciput

**Comment by dimasciput** [comment]
@Fanevanjanahary can you update the colors for the fish too?

**Comment by Fanevanjanahary** [comment]
Hi @jeremyshelton, please can you check on this?
image

**Comment by jeremyshelton** [comment]
@Fanevanjanahary those colors look OK. 
But I would like to see it on the site. 
Production still has RBIS colors & testing site is not loading correctly.
Let me know when it's ready to view on testing (or production)...
Thanks

**Comment by jeremyshelton** [comment]
@Fanevanjanahary this now looks OK on landing page.
Please use FBIS primary colors where possible (this is not presently the case on testing):
161260401-85b2df51-6036-426a-ae12-ada4c2b6029b

Also, for algae, please replace the category called 'Null' with 'Unknown'

Then we can deploy to production site.
Thanks

**Pull request merged**
