### PR TITLE
call getfeatureinfo when click map

### PR DESCRIPTION
**Pull request by meomancer**
this fix kartoza/LEDET_BIMS/issues/229

Call getFeatureInfo when map is clicked.
But, we need to show layers first before able to get it. (is this right or should we show all layers info without checking the layers are visible @gubuntu ?)

Maybe we better show it on side panel?

TODO: Fixing tab (maybe trying to represents like chrome)

selection_122
selection_123
selection_124

### CODE REVIEW

**Comment by dimasciput** [comment]
@meomancer 

> But, we need to show layers first before able to get it. (is this right or should we show all layers info without checking the layers are visible @gubuntu ?)

I think that's a correct behavior.

> TODO: Fixing tab (maybe trying to represents like chrome)

https://getbootstrap.com/docs/3.3/components/#nav-tabs

**Comment by meomancer** [comment]
hi @dimasciput 
Updated:

When 1 tab:


When 2 tab:
selection_128

If tabs are bigger than the navbar:
selection_129
selection_130

**Comment by dimasciput** [comment]
@meomancer looks great, thanks!

**Comment by gubuntu** [comment]
This is fine for now but I think we should be doing a full drilldown of all available layers (like a local GeoContext). But to do that nicely we need to return nicely formatted data from selected fields, which can be done on the geoserver side with templates or within the popup.

**Pull request merged**
