### PR TITLE
Update species detail

### PR DESCRIPTION
**Pull request by meomancer**
this PR for : https://github.com/kartoza/LEDET_BIMS/issues/169

Updates:
- Relayouting side panel to use 100% height (last one was not good height)
- Add species detail when we click taxa on search result.

selection_035
selection_036
selection_037

Note: 
The color of IUCN status is based on sensitive value. I think we need colouring system for these status (like "Near Threatened" should be yellow)

based on moqups : https://app.moqups.com/tim@kartoza.com/47tU30vEA3/edit/page/a417f257a
but still not sure for other fields:
- "Native" value
- Species richness
- Shannon Diversity
- Simpson Diversity

### CODE REVIEW

**Comment by gubuntu** [comment]
Looking great

**Comment by dimasciput** [comment]
@meomancer looks great

screen shot 2018-08-11 at 7 23 16 pm

I think `Near Threatened` should be red.

**Comment by meomancer** [comment]
hi @dimasciput 
the color is softcoded, based on the sensitive status
and NT is not sensitive

I think we could add new field on iucn model, "colour" field which filled by color of iucn status
or maybe new field "threat level" and the colours determined by threat level (green-yellow-red)

what do you think?

**Comment by dimasciput** [comment]
@meomancer yes I think that's a god idea, thanks

**Comment by meomancer** [comment]
Updated @dimasciput

**Pull request merged**
