### PR TITLE
Filter occurrences by data_type

### PR DESCRIPTION
**Pull request by dimasciput**
For https://github.com/kartoza/django-bims/issues/3598

### CODE REVIEW

**Comment by dimasciput** [comment]
@helendallas 

When this is deployed, the filter will now also check the data type:

- **Public or empty data type:**
All users will be able to see the data.

- **Private**:
All the staff of the tenant site will be able to see the data. For example, Sanparks staff will be able to see Sanparks occurrence data with the data type set to private.
Additionally, I have added a new group called SensitiveDataGroup. If a regular user is added to this group, they will also be able to see private data.

- **Sensitive**:
I have added a new group called SensitiveDataGroup. If a user is added to this group, they will be able to see sensitive data.

The new groups : 

image

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 13 min

**Comment by helendallas** [comment]
Ok sounds good. Let me know when deployed.

Question: So one or more users can be added to SensitiveDataGroup. 

What if this has to be per Taxon. So for example only two SANParks users can see Rhino data, but then a different two can see Cycad data. I would imagine this may be the case.  Would we then need to have different SensitiveDataGroup per taxon.

**Comment by dimasciput** [comment]
@helendallas 

> Question: So one or more users can be added to SensitiveDataGroup.

Yes, one or more users can be added to the SensitiveDataGroup.

> What if this has to be per Taxon. So for example only two SANParks users can see Rhino data, but then a different two can see Cycad data. I would imagine this may be the case. Would we then need to have different SensitiveDataGroup per taxon.

This will overcomplicate the query because we currently do permission checking at the occurrence level. If we want it at the taxon level, I will have to think another solution. It could take 2-3 days to implement and might also slow down the query. I suggest we demo this to the client before implementing another feature.

We also need to add some UI in the taxon management page to add user to the groups that they can see.

**Comment by helendallas** [comment]
Okay thanks Dimas. Agreed. For now let's leave it as it is. 

They have asked for a few other bells and whistles and have requested we provide a budget for this extra work that they will try and find extra funds for. I will suggest that if they want this then they will need to find extra funds.

**Comment by helendallas** [comment]
Screenshot 2024-08-12 at 12 40 43


@dimasciput What is SANParks group here??? Is that the public group?  It's a bit misleading if it is.

Please clarify

**Comment by dimasciput** [comment]
@helendallas I'm not sure what group is that, I think we can remove it. Probably created for testing. I will check and remove it.

**Comment by helendallas** [comment]
THanks

**Pull request merged**
