### PR TITLE
update filter view

### PR DESCRIPTION
**Pull request by meomancer**
this fix #https://github.com/kartoza/django-bims/issues/137

This update filter view.
Updates:
- Search can be just filter by date without needs keyword.
- Side panel is resulting based on filter. (taxa is stll empty. Should we remove it, because records already grouping by taxa). Sites is show too, but still not sure what to do when we click it.

Screenshot:
selection_016

Demo:
https://drive.google.com/file/d/1q1jtCQ83mg7oI7tbYhnch3uZ_0P0maep/view?usp=sharing

Note:
- The search view is not using haystack, instead using django query. I'm still not sure how to search by year and by month on haystack. Maybe we create new ticket and need @ann26 help?

### CODE REVIEW

**Comment by meomancer** [comment]
good morning @ann26 
Could you help me update search api, so it can be filter by year and by months?

query year like this
https://github.com/meomancer/django-bims/blob/92d238825244b75420d9558fc3ae8751b6ae4bf8/bims/api_views/cluster_collection.py#L68

query month like this
https://github.com/meomancer/django-bims/blob/92d238825244b75420d9558fc3ae8751b6ae4bf8/bims/api_views/cluster_collection.py#L80

**Comment by ann26** [comment]
ok @meomancer

**Comment by cchristelis** [comment]
@meomancer and @ann26, please create a new ticket and size it and add `requires #xx` rather than doing a double assign on this ticket.

**Comment by dimasciput** [comment]
@meomancer have you fix this?

**Comment by meomancer** [comment]
hi @dimasciput yes, could you try it?

**Comment by meomancer** [comment]
here some screenshots @dimasciput 
screenshot from 2018-07-19 15 46 08
screenshot from 2018-07-19 15 46 24
screenshot from 2018-07-19 15 46 44
screenshot from 2018-07-19 15 48 10
screenshot from 2018-07-19 15 48 33
screenshot from 2018-07-19 15 48 46
screenshot from 2018-07-19 15 48 54

**Pull request merged**
