### PR TITLE
catchment area

### PR DESCRIPTION
**Pull request by ann26**
fix https://github.com/kartoza/healthyrivers/issues/138

### CODE REVIEW

**Comment by cchristelis** [comment]
Hi @ann26, could you drop a gif here, please.

**Comment by ann26** [comment]
hi @cchristelis here's gif for the UI
peek 2018-08-20 08-49

**Comment by meomancer** [comment]
hi @cchristelis 
it is not done yet. The query is not in this PR, but in here
https://github.com/ann26/django-bims/pull/1

**Comment by meomancer** [comment]
hi @cchristelis 
Updated with selection of catchment area (boundary)
and also filters it

https://drive.google.com/file/d/1y4n8h6CEQxQRF176PjtC-sKH8DHJIUXG/view?usp=sharing

**Pull request merged**
