### PR TITLE
Fix downloads in dashboards

### LINKED ISSUE #2444: Chart downloads not working in dashboards
@dimasciput 
@helendallas 

When I click on download chart, nothing happens.

Screenshot 2020-12-08 at 06 11 57

### PR DESCRIPTION
**Pull request by Fanevanjanahary**
Fix #2444

### CODE REVIEW

**Comment by dimasciput** [comment]
@Fanevanjanahary can you share a gif or screenshot?

**Comment by Fanevanjanahary** [comment]
- Occurrences Chart
occurrences


- Occurrence data
occurrence-data



- Overview
overview


- Metadata table
metadata

**Comment by dimasciput** [comment]
LGTM @Fanevanjanahary , thanks

**Comment by dimasciput** [comment]
Thanks @Fanevanjanahary

**Pull request merged**
