### PR TITLE
make levels on boundary and use it to calculate cluster

### PR DESCRIPTION
**Pull request by meomancer**
hi @timlinux @dimasciput 
This PR is about improving calculation of cluster.
Instead of generating cluster per boundary, it is just generate cluster for lowest administrative boundary (municipals)
For the upper administrative, it is calculating based on the lower administrative.

For example : 
- We have district A, which has municipals A1, A2, A3.
- On update cluster, cluster generated for A1, A2, A3
- On district A, it will just calculate by the value on A1, A2, A3.

What this PR updates:
- Update boundary to has field 'top_level_boundary', which is what boundary that in top of it (what district for boundary municipal)
- Update calculation of update_cluster

With this, we reduce querying on top level of administrative.

selection_013
selection_014

### CODE REVIEW

**Comment by timlinux** [comment]
Nice - just note that it is not always guaranteed that the boundaries will be spatially nested

For LEDET it will be for HealthyRivers the catchments can span districts. I think we can make the call and go with your approach and work with the client to use nested boundaries.

**Comment by dimasciput** [comment]
@meomancer I got this `bims.models.boundary_type.MultipleObjectsReturned: get() returned more than one BoundaryType -- it returned 4!` when running the code

**Comment by dimasciput** [comment]
When I run ` python manage.py update_provinces_boundary`, I got this error message : 

```
  File "/home/web/django_project/bims/management/commands/update_provinces_boundary.py", line 20, in handle
    'province', 'provname', 'prov_code', 2, 'country')
  File "/home/web/django_project/bims/management/commands/update_boundary.py", line 82, in save_data
    column_top_boundary].value
  File "/usr/local/lib/python2.7/site-packages/django/contrib/gis/gdal/feature.py", line 39, in __getitem__
    i = self.index(index)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/gis/gdal/feature.py", line 116, in index
    raise OGRIndexError('invalid OFT field name given: "%s"' % field_name)
django.contrib.gis.gdal.error.OGRIndexError: 'invalid OFT field name given: "country"'
```

**Comment by meomancer** [comment]
hi @dimasciput @timlinux 
fixed and updated:
- Note : I found that some municipals has same name with different district, so i changed the unique to use codename instead.
- @dimasciput need to emptying all boundary data first

**Comment by dimasciput** [comment]
LGTM

**Comment by timlinux** [comment]
LGTM - please make sure to document the behaviour. @dimasciput can you start a docs/ folder (if we dont already have one) and require that PR's come accompanied with screenshots and documentation of the feature. Don't worry about perfect english. @gubuntu and I can clean up the english after.

**Pull request merged**
