### PR TITLE
[WIP] GeoNode deep integration

### PR DESCRIPTION
**Pull request by lucernae**
First pass effort of GeoNode integration.
Current changes:

- Merge Django BIMS docker image with GeoNode Generic
- Add GeoNode + Geoserver orchestration in docker-compose file
- Add GeoNode + Geoserver to Ansible project setup
- Merged root urls.py and settings.py
- Added hack/workaround to fix incompatibility between GeoNode's celery workflow with rolepermissions apps

### CODE REVIEW

**Comment by lucernae** [comment]
Also closes #66

**Comment by dimasciput** [comment]
@lucernae Yes I agree, we can create different PR for those issues. Let's merge this one.

**Comment by timlinux** [comment]
I'm happy to merge this too and figure out the next bits later:

> For example, we need to refactor all User related models/foreign key to GeoNode's User (Profile model). Not just User, but all functionality that is already covered by GeoNode, which includes:

> User
> Permission/Auth
> I18n

Yeah exactly we should link to the geonode models so these permissions and profiles are available / used in BIMS

**Comment by gubuntu** [comment]
@lucernae can you confirm you are using the geonode-project template?

**Pull request merged**
