### PR TITLE
Show geocontext on click

### PR DESCRIPTION
**Pull request by dimasciput**

### CODE REVIEW

**Comment by timlinux** [comment]
Is this ready to merge @dimasciput ? Did you manage to tidy the popup appearance?

**Comment by dimasciput** [comment]
@timlinux yes it looks like this
screen shot 2018-05-22 at 9 46 24 am

**Comment by gubuntu** [comment]
this is currently broken on staging

**Comment by gubuntu** [comment]
closes https://github.com/kartoza/LEDET_BIMS/issues/82

**Pull request merged**
