### PR TITLE
show clustering on map

### PR DESCRIPTION
**Pull request by meomancer**
this fix #https://github.com/kartoza/LEDET_BIMS/issues/26
using clustering

selection_016
selection_017
selection_018

DEMO:
https://drive.google.com/file/d/13dggJmAdTRwmZMoLlHlXxzst5-B6S5sG/view?usp=sharing

NOTE:
We need to run at the project setup, because clustering is happening when record is saved (due to getting module)

So the flow
Save boundaries with below command -> when record saved, clustering happened
```
python manage.py update_countries_boundary
python manage.py update_provinces_boundary
python manage.py update_districts_boundary
python manage.py update_municipals_boundary
```

### CODE REVIEW

**Comment by timlinux** [comment]
Looking good @meomancer ! So will cluster computation also happen when we do CRUD? I guess we need to do that smart by only recomputing clusters for areas that the site intersects with....

**Comment by meomancer** [comment]
hi @timlinux 
ah, not for delete, will update it

yes, it is just updating the cluster where the record site

**Comment by meomancer** [comment]
Updates:
- add 'update cluster' command 
- update cluster when record deleted
- update when location sites CRUD

**Comment by dimasciput** [comment]
Tested, and it's working, to do list for another PR : 
- [ ] Request collection based on bbox

**Pull request merged**
