### PR TITLE
Update module summary data in landing page dashboard

### LINKED ISSUE #2945: Landing page dashboard
At the moment, Dimas needs to specify what is visualised, i.e. origin, Ecological category, conservation status etc.

Two requests related to this:

Firstly, fish and anurans should both be by Conservation Status, and Algae by Division

Secondly, Is it possible to develop functionality in Admin where we can choose what to display?  Let's chat this through. If an easy task, then action, if it is going to take a long time, then let's leave for now.

### PR DESCRIPTION
**Pull request by Fanevanjanahary**
fixes  #2945

### CODE REVIEW

**Comment by dimasciput** [comment]
@Fanevanjanahary please add screenshots for the charts.

**Comment by Fanevanjanahary** [comment]
Hi @dimasciput, for now, I haven't updated the front end yet. Should I? 

image

**Comment by dimasciput** [comment]
@Fanevanjanahary yes please, thanks

**Comment by Fanevanjanahary** [comment]
Peek 2022-07-27 14-26

**Pull request merged**
