### PR TITLE
fix mobile layout

### PR DESCRIPTION
**Pull request by ann26**
fix https://github.com/kartoza/LEDET_BIMS/issues/46

img_9554
img_9556
img_9555

img_9550
img_9551
img_9552
img_9553

### CODE REVIEW

**Comment by dimasciput** [comment]
Hi @ann26 , nice work. The menu still looks big in mobile device. 
You should edit the css using media queries, https://www.w3schools.com/css/css3_mediaqueries_ex.asp.

**Comment by ann26** [comment]
@dimasciput how about this?
image from ios
image from ios 1
image from ios 2
image from ios

**Comment by dimasciput** [comment]
@ann26 

screen shot 2018-07-24 at 10 57 29 am

**Comment by ann26** [comment]
@dimasciput 
screenshot from 2018-07-24 15-04-05

**Pull request merged**
