### PR TITLE
Improve graphics quality for chart downloads

### PR DESCRIPTION
**Pull request by dimasciput**
For #1217 

This is still only for single SASS dashboard for now.

One example of the chart : 
[Proportion of sensitive to tolerant taxa.pdf](https://github.com/kartoza/django-bims/files/4243737/Proportion.of.sensitive.to.tolerant.taxa.pdf)

### CODE REVIEW

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas , what do you think of the chart? This is still not deployed to testing or live server yet.

**Comment by helendallas** [comment]
@dimasciput Quality looks good to me. Only comment would be larger key/font relative to graphic.
@jeremyshelton ?

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas FYI that this problem is pretty complicated on the technical side, the way I resolve this problem is to create svg on the frontend (usually users don't know how to open svg files) then push it to the server for processing into pdf file.
So the layout will not matched perfectly with what you saw in the dashboard, but since the chart is in vector, you can zoom it as much as you want and the quality is still the same. 
And I only do this on one dashboard, because it will require more time to update all dashboards.

cc @timlinux

**Comment by jeremyshelton** [comment]
@dimasciput @helendallas @timlinux 
Good quality, clear, consistent, downloadable graphs is what the users need for their reports, and a big part of the appeal of the system, so it's definitely worth figuring this one out if at all possible.

I agree with @helendallas that the quality in the converted svg looks good & scalability is a big plus.

I think I understand the problem & it sounds like a tricky one to solve: is there any way to get the axis labels looking like they do in the dashboard? Or at least more similar than this: a bit bigger font size, solid black & slightly repositioned to line up better with the axes? 

Also, no FBIS logo needed for this. However, it would be nice to include text 'Downloaded by user XX from the Freshwater Biodiversity Information System (FIBIS) on 26 February 2020' above or below the graphic...

Also, do you guys thing the user download should be a PDF or a PNG?

**Comment by dimasciput** [comment]
With pdf, the image quality will not be lost when zooming the image. Because it stored as a vector. 

>  However, it would be nice to include text 'Downloaded by user XX from the Freshwater Biodiversity Information System (FBIS) on 26 February 2020' above or below the graphic...

I'm not sure I understand what the benefit of this, because the user is not generating the chart. The date is still makes sound though.

You can try to download the charts here : http://testing.healthyrivers.kartoza.com/sass/dashboard/10425/?siteId=10425

This task is getting more complicated than others if we want really perfect results.

**Comment by jeremyshelton** [comment]
@dimasciput yeah ok, don't worry about:

_However, it would be nice to include text 'Downloaded by user XX from the Freshwater Biodiversity Information System (FBIS) on 26 February 2020' above or below the graphic..._

Rather for now lets (1) try get the font sorted (bigger font size, solid black & slightly repositioned to line up better with the axes), and (2) remove the logo from downloads. 

Other than that, quality looking good...

**Comment by timlinux** [comment]
I would prefer an approach where we deliver the raw svg to the user and then share them a message pointing them to use either a service like https://svgtopng.com or a free tool like Inkscape.

https://inkscape.org

**Pull request merged**
