### PR TITLE
Monitoring Dashboard

### PR DESCRIPTION
**Pull request by sonlinux**
fix kartoza/LEDET_BIMS#45

### CODE REVIEW

**Comment by timlinux** [comment]
@sonlinux I want to suggest some changes to your workflow to make all of our lives easier 

1. Enable travis in your fork of bims 
2. Make PR's to your own repo
3. Get testing working etc in your repo and generally get everything merge ready 
4. Make a PR to the main repo

**Comment by sonlinux** [comment]
Statistics page

stats

**Comment by gubuntu** [comment]
@sonlinux assign someone to review this then get it merged and deployed asap

**Comment by sonlinux** [comment]
Okay @gubuntu

**Comment by sonlinux** [comment]
Hi @dimasciput 
Please review this when you can.
Thanks

**Comment by gubuntu** [comment]
@sonlinux you hadn't assigned it, I've just done so. Is there anything to see on testing?

**Comment by cchristelis** [comment]
@sonlinux, please update this PR.

**Pull request merged**
