### PR TITLE
add geocontext detail

### PR DESCRIPTION
**Pull request by meomancer**
this fix kartoza/healthyrivers/issues/152

Geocontext is not working (got 502 from it)
So i use dummy data from staging server (there is 1 site that has geocontext)

selection_059

TODO:
- [ ] Relayouting, maybe is there any idea for this @carina1000 ?

### CODE REVIEW

**Comment by cchristelis** [comment]
@meomancer, it is already in the mockups see https://github.com/kartoza/django-bims/pull/248#issuecomment-414309266. The 'details' section is the right place for this...

**Comment by meomancer** [comment]
hi @cchristelis 
that moqups is the dashboard
what i mean is not "where", but how to represent this gecontext value on the UI. 
I just show it like that image in the table format

**Comment by cchristelis** [comment]
@meomancer, please show it in the "Details" section as per the comment above. The context for that site should be part of the details of the site, you can use the site's lat/long for that detail.

**Comment by dimasciput** [comment]
done in https://github.com/kartoza/django-bims/pull/308

**Pull request closed without merging**
