### PR TITLE
Add basemap selection

### PR DESCRIPTION
**Pull request by meomancer**
this fix #https://github.com/kartoza/LEDET_BIMS/issues/65

selection_003
selection_004
selection_005

The basemap list, is it correct?
what is oposheets / topostyle? @gubuntu 

and also, i still can't figure out how to include https://github.com/walkermatt/ol-layerswitcher to require.js, so this PR still using global import

### CODE REVIEW

**Comment by timlinux** [comment]
We should have the SA Toposheets too:

Label: South Africa 1:50k Toposheets
Tile URL: https://htonl.dev.openstreetmap.org/ngi-tiles/tiles/50k/{z}/{x}/{-y}.png

**Comment by timlinux** [comment]
Also  grab selected tiles from https://openmaptiles.org/styles/ if you can and default to the klanotech terrain that would be great or similar.

**Comment by timlinux** [comment]
See also https://mc.bbbike.org/mc/ for more options

**Comment by gubuntu** [comment]
@meomancer I've added the topostyle url to the ticket

**Comment by meomancer** [comment]
hi @timlinux @gubuntu @dimasciput 
updated, added 4 new basemap (not sure what other basemap should i add)

Default : Terrain style (if we provide the MapTiler key)
selection_008
selection_009

Other new basemaps:
selection_010
selection_011
selection_012

**Comment by gubuntu** [comment]
That's fine for now, I think you can close this and move on. We'll tweak it in the next sprint after feedback.

**Pull request merged**
