### PR TITLE
improve cluster query, add administrative boundary

### PR DESCRIPTION
**Pull request by meomancer**
- Improve cluster on administrative level (fasten it)
- show administrative boundary to map (need to run `python manage.py generate_boundary_geojson`)
- Clean code

selection_008
selection_009

### CODE REVIEW

**Comment by dimasciput** [comment]
@meomancer can you the management command in Makefile? Also maybe update the readme to update the boundary.

**Comment by timlinux** [comment]
Are the boundaries being rendered as geojson?

**Comment by timlinux** [comment]
Just a reminder that we should explicitly get the centroinds for boundares as a model field and then let @NyakudyaA give you nice 'natural' centroids and not the current geometrical centroids we have.

**Comment by meomancer** [comment]
hi @timlinux boundaries rendered as geojson, which it is regenerated on backend and saved on file. Because i found that with query, it takes a lot of time to return data (with file, it is faster)

with centroid, yes tim, will update it

**Comment by meomancer** [comment]
hi @dimasciput @timlinux 
updated:
add centroid field:
selection_016

if centroid null:
selection_017

if not null:
selection_018

- also fix based on dimas comment:
- zoom in and focus when cluster clicked
- add makefile for generating boundary

**Comment by dimasciput** [comment]
Tested and it's working, LGTM.

**Pull request merged**
