### PR TITLE
base report PDF

### PR DESCRIPTION
**Pull request by sonlinux**
fix kartoza/LEDET_BIMS#15

### CODE REVIEW

**Comment by timlinux** [comment]
We need tests @sonlinux !

Can you wrap this up as a working, discoverable feature and get it merged ASAP?

Please provide screenshots etc. and sample reports.

**Comment by timlinux** [comment]
Any update on this @sonlinux?

**Comment by dimasciput** [comment]
@sonlinux any updates?

**Comment by sonlinux** [comment]
Hi @dimasciput 
Yes I have the base report coming through with no data on vegetation since we do not have the module yet.


ledet_report

**Comment by sonlinux** [comment]
On the 2 sections below on the PDF I want to add some content

**Comment by timlinux** [comment]
Can you please work with @carina1000 to design the layout of the report properly?

**Comment by sonlinux** [comment]
Alright @timlinux I will do.
Thanks

**Comment by sonlinux** [comment]
## Suggested appearance, combine logo colors
report_looks

**Comment by carina1000** [comment]
@sonlinux although I like the 80s vibe the background is a bit too funky. Lets wait till Gavin reply so I can understand what exactly needs to go on there then I can help you with the design! Lets keep it a bit more simple!

**Comment by sonlinux** [comment]
:smile: Alright @carina1000

**Comment by dimasciput** [comment]
@sonlinux can you update this PR? if you found some difficulties just let me know

**Comment by sonmuko** [comment]
Alright @dimasciput am working on it.
I just got the example report.
Thanks

**Comment by sonlinux** [comment]
Hi @myarjunar 
Could you take over this PR please so that we have it merge-able tomorrow.
thanks

**Comment by cchristelis** [comment]
Hi @sonlinux and @myarjunar the focus of this PR should be to have the reporting Module usable in the system. Let's add actual reports in other PRs esp. where applicable to the various modules.

**Comment by sonlinux** [comment]
Thanks for that clarification @cchristelis.

**Comment by sonlinux** [comment]
report_pdf

**Comment by cchristelis** [comment]
@ann26, are you able use this as a basis for the fish report?

**Pull request closed without merging**
