### PR TITLE
Bibliography management

### PR DESCRIPTION
**Pull request by sonlinux**
fix kartoza/LEDET_BIMS#47

## Menu
menue_final

## Base publications page
biblio_1

## Reference import page
biblio_2

## Administration
biblio_3

- [x] Incorperate app into bims-core

### CODE REVIEW

**Comment by timlinux** [comment]
Same comment as for #28:

@sonlinux please up your game with your PRs:

* Proper reference to upstream tickets
* Screenshots / sample outputs
* Description of the work you have done
* Updates to README / system documentation with notes on how to generate docs


Thanks!

**Comment by timlinux** [comment]
Also, I cannot see how / where it is exposed to the user. How do they navigate to the bibliography?

**Comment by timlinux** [comment]
And of course we need passing tests!

**Comment by ann26** [comment]
@sonlinux I was wondering why you don't just add this app https://github.com/TailorDev/django-tailordev-biblio ?
Also in the menu you can remove `menu 1` and `menu 2`

**Comment by sonlinux** [comment]
Hi @ann26 
It was compatible with django 1.7 and so a lot of changes in its design were not working with django version for this project.
And so the app was not working for this version of django. That is why I had to add it manually.
Thanks
Alright @ann26 I will remove the menus

**Comment by ann26** [comment]
if that's the case then you should remove this https://github.com/kartoza/django-bims/pull/29/files#diff-2eeaed663bd0d25b7e608891384b7298R57

**Comment by sonlinux** [comment]
Ah wonderful! 
Many thanks for that catch @ann26

**Comment by sonlinux** [comment]
Done and its all good now @ann26

**Comment by ann26** [comment]
Hi @sonlinux , thanks for your work. I have several notes here (tested using chrome) :

1. Admin
screenshot from 2018-06-22 10-21-27
Is it possible to make a separate section for this? Or maybe separate app? What do you think @dimasciput ?
The current admin for bibliography is included in bims app, made it cluttered and difficult to manage (as seen in screenshot above). It will be nicer to have separate section for this since the bibliography has several models.

2. Bibliography import is working, but.... I got error when importing using both PubMed Identifiers and DOI. Importing using either PubMed Identifiers or DOI only (single or multiple) is working.

3. Filters are not working.

4. UI
Please style the navbar to look better also it looks smaller than in landing page somehow? :
screenshot from 2018-06-22 10-13-12

Please remove the scroll bar here, it is not needed:
screenshot from 2018-06-22 10-21-44

Also for the import message, maybe you can just add the button somewhere to make it look nicer. The current view is covering the filters collection.
screenshot from 2018-06-22 10-40-54

**Comment by dimasciput** [comment]
> @ann26 The current admin for bibliography is included in bims app, made it cluttered and difficult to manage (as seen in screenshot above). It will be nicer to have separate section for this since the bibliography has several models.

Yes I think we should separate them if it's possible, but I think we can do that in another Pull Request.

@sonlinux can you address Anita's notes?

**Comment by sonlinux** [comment]
Thanks @dimasciput 
Alright ill do so

**Comment by timlinux** [comment]
@ann26 wrote:


> Is it possible to make a separate section for this? Or maybe separate app? What do you think @dimasciput ?


Yes definitely in a separate app....separation of concerns is a basic rule in software development....

Also agree  that the styling should be consistent with the rest of BIMS otherwise it looks like a mish mash of stuff.

**Comment by timlinux** [comment]
@sonlinux lets get this done by today please its already taken waaaaaaaaay longer than expected....

**Comment by timlinux** [comment]
Did you move it into its own admin group @sonlinux ?

@dimasciput can you do a final review and merge if you are happy? Are there any tests for this @sonlinux ?

**Comment by dimasciput** [comment]
@timlinux will do

**Comment by dimasciput** [comment]
LGTM

**Pull request merged**
